name: ci_keyme

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Update KAKAO_NATIVE_APP_KEY from Secrets
        env:
            KAKAO_NATIVE_APP_KEY: $
        run: echo KAKAO_NATIVE_APP_KEY=\"KAKAO_NATIVE_APP_KEY\" > ./local.properties
      - name: App Module ktlintCheck
        run: ./gradlew app:ktlintCheck
      - name: Presentation Module ktlintCheck
        run: ./gradlew presentation:ktlintCheck
      - name: Domain Module ktlintCheck
        run: ./gradlew domain:ktlintCheck
      - name: Data Module ktlintCheck
        run: ./gradlew data:ktlintCheck

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Update KAKAO_NATIVE_APP_KEY from Secrets
      env:
            KAKAO_NATIVE_APP_KEY: $
      run: echo KAKAO_NATIVE_APP_KEY=\"KAKAO_NATIVE_APP_KEY\" > ./local.properties
    - name: Debug Build with Gradle
      run: ./gradlew assembleDebug
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app
        path: app/build/outputs/apk/debug
